name: Terraform apply 
on:
  workflow_dispatch: 
    inputs:
      confirm_deploy:
        description: Type "apply" to confirm deployment'
        required: true 
        type: string

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}


jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_deploy == 'apply'

    defaults:
      run:
        working-directory: ./terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: >
          terraform init \
            -backend-config="bucket=${{ secrets.TERRAFORM_STATE_BUCKET }}" \
            -backend-config="key=${{ secrets.TERRAFORM_STATE_KEY }}" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="encrypt=true"

    - name: Terraform Validate
      working-directory: ./terraform
      run: terraform validate

    - name: Terraform Plan
      working-directory: ./terraform
      run: |
        terraform plan \
          -var="domain_name=${{ vars.DOMAIN_NAME }}" \
          -var="project_name=${{ vars.PROJECT_NAME }}" \
          -var="record_name=${{ vars.RECORD_NAME }}" \
          -var="task_role_arn=${{ secrets.TASK_ROLE_ARN }}" \
          -var="execution_role_arn=${{ secrets.EXECUTION_ROLE_ARN }}" \
          -var="container_image=${{ secrets.CONTAINER_IMAGE }}" \
          -input=false \
          -out=tfplan

          


    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve tfplan


        