name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "destroy-all" to confirm infrastructure destruction'
        required: true
        type: string

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  

jobs:
  terraform:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_destroy == 'destroy-all'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0

    - name: Terraform Init
      run: terraform init -reconfigure -backend-config="backend.hcl"

    - name: Terraform Plan Destroy
      run: terraform plan -destroy -no-color

    - name: Terraform Destroy
      run: terraform destroy -auto-approve

    - name: Destroy Confirmation
      if: success()
      run: echo "Infrastructure has been successfully destroyed!"

    - name: Destroy Failed
      if: failure()
      run: echo "Destroy failed! Check the logs above for more information."