name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "destroy" to confirm infrastructure destruction'
        required: true
        type: string

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  

jobs:
  terraform:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_destroy == 'destroy'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0

    - name: Terraform Init
      working-directory: ./terraform
      run: >
            terraform init \
              -backend-config="bucket=${{ secrets.TERRAFORM_STATE_BUCKET }}" \
              -backend-config="key=${{ secrets.TERRAFORM_STATE_KEY }}" \
              -backend-config="region=${{ secrets.AWS_REGION }}" \
              -backend-config="encrypt=true"

    - name: Terraform Plan Destroy
      working-directory: ./terraform
      run: terraform plan -destroy -out=tfdestroyplan        
  

    - name: Terraform Destroy alb first
      working-directory: ./terraform
      run: |
       terraform destroy -target="module.alb.aws_lb.this" -auto-approve \
         -var="container_image=${{ secrets.CONTAINER_IMAGE }}" \
        -var="domain_name=${{ vars.DOMAIN_NAME }}" \
        -var="project_name=${{ vars.PROJECT_NAME }}" \
        -var="record_name=${{ vars.RECORD_NAME }}" \
        -var="task_role_arn=${{ secrets.TASK_ROLE_ARN }}" \
        -var="execution_role_arn=${{ secrets.EXECUTION_ROLE_ARN }}"

    - name: Terraform Destroy
      working-directory: ./terraform
      run: terraform apply -auto-approve tfdestroyplan


    - name: Destroy Confirmation
      if: success()
      run: echo "Infrastructure has been successfully destroyed!"

    - name: Destroy Failed
      if: failure()
      run: echo "Destroy failed! Check the logs above for more information."